export const POPULATE_PLAYERS = "[PLAYER] POPULATE_PLAYERS";
export const ADD_PLAYER = "[PLAYER] ADD_PLAYER";
export const REMOVE_PLAYER = "[PLAYER] REMOVE_PLAYER";
export const SET_PLAYERS = "[PLAYER] SET_PLAYERS";
